Raise PHPStan level to 9
ondrejmirtes/simple-downgrader pull request #4
Opened 2024-01-08 15:15 UTC by clxmstaab

raise to level 9 for max safety.

I tried locally reverting the fix from https://github.com/ondrejmirtes/simple-downgrader/commit/6a8d0f0c1a4fae734f03161d3d19d7437058ca0b but level 9 still does not catch it

refs https://github.com/ondrejmirtes/simple-downgrader/pull/3/files#r1444030185

2024-01-08 15:21 UTC, clxmstaab commented
with `checkImplicitMixed: true` it would be catched

2024-01-08 15:35 UTC, ondrejmirtes requested changes
1) Try checkImplicitMixed too
2) Try fixing the errors instead of the baseline

2024-01-08 17:09 UTC, staabm commented
@ondrejmirtes done

2024-01-08 17:18 UTC, staabm commented on phpstan-baseline.neon
> +			message: "#^Method SimpleDowngrader\\\\PhpDoc\\\\CallbackVisitor\\:\\:enterNode\\(\\) should return 1\\|2\\|3\\|4\\|array\\<PHPStan\\\\PhpDocParser\\\\Ast\\\\Node\\>\\|PHPStan\\\\PhpDocParser\\\\A
see https://github.com/phpstan/phpstan/issues/10409

2024-01-09 12:23 UTC, ondrejmirtes approved these changes

2024-01-09 12:24 UTC, merged

2024-01-09 12:24 UTC, ondrejmirtes commented
Thank you.